---
title: "Display map of pixels"
author: "AJ Perez-Luque (@ajpelu)"
date: "2016 August"
output: html_document
---


```{r wd, echo=FALSE}
#---------------------------------
machine <- 'ajpelu'
# machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/phd/phd_repos/modis_iv', sep='')
#---------------------------------
```

```{r packages, warning=FALSE, message=FALSE, echo=FALSE}
library("rgdal")
library("sp")
library("raster")
library("leaflet")
library("dplyr")
```

```{r, readData, echo=FALSE}
# Polygonine. SEE this tutorial http://neondataskills.org/working-with-field-data/Field-Data-Polygons-From-Centroids 

# Prepare spatial data 
iv <- read.csv(file=paste0(di,"/data_raw/coord_qpyr.csv"), header=TRUE, sep=",")
# rename 
names(iv) <- c('iv_malla_modi_id','x','y', 'pob')

# Set coordinates 
coordinates(iv) <- c('x', 'y') 
# Set projection 
proj4string(iv) <- CRS("+init=epsg:4326") 
# Reproject 
iv_re <- spTransform(iv, CRS("+init=epsg:23030")) 

# Get dataframe 
ivdf <- as.data.frame(iv_re)

# Define radius 
radius <- 250/2

# define the boundaries around each centroide 
yPlus <- ivdf$y+radius
xPlus <- ivdf$x+radius
yMinus <- ivdf$y-radius
xMinus <- ivdf$x-radius

# Create a closed polygon (five points, first and last are equal )
square=cbind(xMinus,yPlus, xPlus,yPlus, xPlus,yMinus, xMinus,yMinus,xMinus,yPlus,xMinus,yPlus)

ID <- ivdf$iv_malla_modi_id

# Option 1 (more efficient ) 
#create spatial polygons
polys <- SpatialPolygons(
  mapply(function(poly, id) {
  xy <- matrix(poly, ncol=2, byrow=TRUE)
  Polygons(list(Polygon(xy)), ID=id)
}, split(square, row(square)), ID),
 proj4string=CRS(as.character("+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")))

# Create SpatilPolygonDataFrame -- this step is required to output multiple polygons.
polys.df <- SpatialPolygonsDataFrame(polys, data.frame(id=ID, row.names=ID))




# # Option 2 (less efficient )
# a <- vector('list', length(2))
# 
# # loop through each centroid value and create a polygon
# for (i in 1:nrow(ivdf)) {
#  a[[i]]<-Polygons(list(Polygon(matrix(square[i, ], ncol=2, byrow=TRUE))), ID[i])
# }
# 
# polys<-SpatialPolygons(a,
#                        proj4string=CRS(as.character("+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")))

# Reproject 
aux_polys <- spTransform(polys.df, CRS("+init=epsg:4326"))

```


```{r, echo=FALSE}
# Map the polygons 
m <- leaflet() %>% 
  addWMSTiles('http://www.ideandalucia.es/services/toporaster10/wms?',
              layers = 'toporaster10',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'Topographical') %>%
  
  addTiles(urlTemplate = "http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
            attribution = '<a href="https://carto.com/attributions">CARTO</a>',
           group = 'Basemap') %>%
  
  addProviderTiles("Esri.WorldImagery", group='Satellite') %>% 
  
    # Layers control
  addLayersControl(position = 'bottomright',
                   baseGroups = c("Topographical","Basemap", "Satellite"),
                   overlayGroups = 'Pixel MODIS', 
                   options = layersControlOptions(collapsed = FALSE)) %>%
  
  addPolygons(data = aux_polys, 
              popup=paste0("<strong>iv_malla_modi_id: </strong>", aux_polys$id), 
              group='Pixel MODIS')
              
m


# # SEE some urls: 
# http://amsantac.co/blog/en/r/2015/08/11/leaflet-R.html
# http://spatialrecology.org/posts/leafletmapping.html
# https://rstudio.github.io/leaflet/basemaps.html

```



```{r, eval=FALSE, echo=FALSE}

# Create a spatial dataframe 
iv_sp <- SpatialPointsDataFrame(coords = iv[,c('lng','lat')], data = iv,
                               proj4string = CRS("+init=epsg:4326"))

# Transform 
aux_spatial <- spTransform(iv_sp, CRS("+init=epsg:23030"))

# raster auxiliar 
aux_rast <- raster(aux_spatial, resolution=230)

# Rasterize 
my_raster <- rasterize(aux_spatial, aux_rast, "poblacion")
names(my_raster) <- "poblacion" 
 
# reproject 
r<- projectRaster(my_raster, crs=crs("+init=epsg:4326"))
plot(r)

# Raster to polygon 
qp <- rasterToPolygons(r)

qp <- sp::merge(x=qp, y=iv, by="iv_malla_modi_id")

x <- length(!is.na(r))
```
